schema_version = "1.0.0"

id = "node_runner"
version = "1.0.0"
name = "Node Runner"
tagline = "Import and export shader & geometry nodes as a string"
maintainer = "Noah Thiering <noah.thiering@gmail.com>"

type = "add-on"

tags = ["Node", "Material", "Geometry Nodes"]

blender_version_min = "5.0.0"

# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
clipboard = "Copy Node Runner Hash to clipboard"
